<?php

return array (
      1 =>
      array (
        1 =>
        array (
          'id' => '1',
          'card_id' => '1',
          'level' => '1',
          'experience' => '0',
          'attack_min' => '36',
          'attack_max' => '46',
          'crit' => '0.1',
          'crit_damage' => '1.5',
          'hp' => '245',
          'accuracy' => '0.15',
          'attack' => '44',
        ),
        2 =>
        array (
          'id' => '2',
          'card_id' => '1',
          'level' => '2',
          'experience' => '100',
          'attack_min' => '44',
          'attack_max' => '56',
          'crit' => '0.1',
          'crit_damage' => '1.5',
          'hp' => '296',
          'accuracy' => '0.15',
          'attack' => '53',
        ),
        3 =>
        array (
          'id' => '3',
          'card_id' => '1',
          'level' => '3',
          'experience' => '200',
          'attack_min' => '53',
          'attack_max' => '68',
          'crit' => '0.1',
          'crit_damage' => '1.5',
          'hp' => '355',
          'accuracy' => '0.15',
          'attack' => '64',
        ),
        4 =>
        array (
          'id' => '4',
          'card_id' => '1',
          'level' => '4',
          'experience' => '300',
          'attack_min' => '64',
          'attack_max' => '83',
          'crit' => '0.1',
          'crit_damage' => '1.5',
          'hp' => '426',
          'accuracy' => '0.15',
          'attack' => '78',
        ),
        5 =>
        array (
          'id' => '5',
          'card_id' => '1',
          'level' => '5',
          'experience' => '400',
          'attack_min' => '77',
          'attack_max' => '101',
          'crit' => '0.1',
          'crit_damage' => '1.5',
          'hp' => '511',
          'accuracy' => '0.15',
          'attack' => '95',
        ),
      ),
      2 =>
      array (
        1 =>
        array (
          'id' => '6',
          'card_id' => '2',
          'level' => '1',
          'experience' => '0',
          'attack_min' => '24',
          'attack_max' => '34',
          'crit' => '0.25',
          'crit_damage' => '1.5',
          'hp' => '270',
          'accuracy' => '0.2',
          'attack' => '38',
        ),
        2 =>
        array (
          'id' => '7',
          'card_id' => '2',
          'level' => '2',
          'experience' => '100',
          'attack_min' => '30',
          'attack_max' => '42',
          'crit' => '0.25',
          'crit_damage' => '1.5',
          'hp' => '328',
          'accuracy' => '0.2',
          'attack' => '47',
        ),
        3 =>
        array (
          'id' => '8',
          'card_id' => '2',
          'level' => '3',
          'experience' => '200',
          'attack_min' => '36',
          'attack_max' => '52',
          'crit' => '0.25',
          'crit_damage' => '1.5',
          'hp' => '394',
          'accuracy' => '0.2',
          'attack' => '57',
        ),
        4 =>
        array (
          'id' => '9',
          'card_id' => '2',
          'level' => '4',
          'experience' => '300',
          'attack_min' => '43',
          'attack_max' => '64',
          'crit' => '0.25',
          'crit_damage' => '1.5',
          'hp' => '473',
          'accuracy' => '0.2',
          'attack' => '70',
        ),
        5 =>
        array (
          'id' => '10',
          'card_id' => '2',
          'level' => '5',
          'experience' => '400',
          'attack_min' => '52',
          'attack_max' => '78',
          'crit' => '0.25',
          'crit_damage' => '1.5',
          'hp' => '568',
          'accuracy' => '0.2',
          'attack' => '85',
        ),
      ),
      3 =>
      array (
        1 =>
        array (
          'id' => '11',
          'card_id' => '3',
          'level' => '1',
          'experience' => '0',
          'attack_min' => '27',
          'attack_max' => '37',
          'crit' => '0.22',
          'crit_damage' => '1.5',
          'hp' => '260',
          'accuracy' => '0.22',
          'attack' => '41',
        ),
        2 =>
        array (
          'id' => '12',
          'card_id' => '3',
          'level' => '2',
          'experience' => '100',
          'attack_min' => '31',
          'attack_max' => '43',
          'crit' => '0.22',
          'crit_damage' => '1.5',
          'hp' => '307',
          'accuracy' => '0.22',
          'attack' => '47',
        ),
        3 =>
        array (
          'id' => '13',
          'card_id' => '3',
          'level' => '3',
          'experience' => '200',
          'attack_min' => '37',
          'attack_max' => '50',
          'crit' => '0.22',
          'crit_damage' => '1.5',
          'hp' => '368',
          'accuracy' => '0.22',
          'attack' => '56',
        ),
        4 =>
        array (
          'id' => '14',
          'card_id' => '3',
          'level' => '4',
          'experience' => '300',
          'attack_min' => '44',
          'attack_max' => '59',
          'crit' => '0.22',
          'crit_damage' => '1.5',
          'hp' => '442',
          'accuracy' => '0.22',
          'attack' => '66',
        ),
        5 =>
        array (
          'id' => '15',
          'card_id' => '3',
          'level' => '5',
          'experience' => '400',
          'attack_min' => '53',
          'attack_max' => '70',
          'crit' => '0.22',
          'crit_damage' => '1.5',
          'hp' => '530',
          'accuracy' => '0.22',
          'attack' => '79',
        ),
      ),
    );